File Edit Options Buffers Tools Help                                                                                                                                                                                                      
#!/user/bin/perl                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          
use v5.10;                                                                                                                                                                                                                                
use File::Basename;                                                                                                                                                                                                                       
use Cwd;                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                          
# ==============                                                                                                                                                                                                                          
$run = 1;                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                          
# Grammar/output conventions                                                                                                                                                                                                              
$sep = "========================================";                                                                                                                                                                                        
                                                                                                                                                                                                                                          
# ==============                                                                                                                                                                                                                          
# Grammar/output conventions                                                                                                                                                                                                              
$sep = "========================================";                                                                                                                                                                                        
                                                                                                                                                                                                                                          
@months = qw( Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec );                                                                                                                                                                          
@days = qw(Sun Mon Tue Wed Thu Fri Sat Sun);                                                                                                                                                                                              
                                                                                                                                                                                                                                          
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();                                                                                                                                                                      
                                                                                                                                                                                                                                          
my $dateidentifier = "${mday}-$months[$mon]-$days[$wday]-$hour-$min-$sec";                                                                                                                                                                
                                                                                                                                                                                                                                          
# ==============                                                                                                                                                                                                                          
$dir = "/clusternfs/ldavis/Phase_Sep_Polymers";                                                                                                                                                                                           
$target_dir = "/clusternfs/ldavis/Phase_Sep_Polymers/xyzdata/twoclustersmicelle";                                                                                                                                                         
$localdir = "/local/ldavis/Phase_Sep_Polymers/xyzdata";                                                                                                                                                                                   
                                                                                                                                                                                                                                          
$generic_infile = "";                                                                                                                                                                                                                     
$genericlaunchfile = "${dir}/launch_generic.sh";                                                                                                                                                                                          
                                                                                                                                                                                                                                          
#my $nodename = "hpc10";                                                                                                                                                                                                                  
                                                                                                                                                                                                                                          
my $runstring = "cp ${localdir}/micellex2*.xyz ${target_dir}/";                                                                                                                                                                           
                                                                                                                                                                                                                                          
my $nodeprefix = 'hpc';                                                                                                                                                                                                                   
my @nodeindices = (1..16);                                                                                                                                                                                                                
                                                                                                                                                                                                                                          
foreach $nodeindex (@nodeindices){                                                                                                                                                                                                        
                                                                                                                                                                                                                                          
    my $nodename = ${nodeprefix}.${nodeindex};                                                                                                                                                                                            
    my $sbatchflags = " -w $nodename";                                                                                                                                                                                                    
    my $jobname = "Data-slurp-${nodename}";                                                                                                                                                                                               
    my $dd='30';                                                                                                                                                                                                                          
    my $hh='00';                                                                                                                                                                                                                          
    my $mm='00';                                                                                                                                                                                                                          
    my $ss='00';                                                                                                                                                                                                                          
    my $email='luke.davis@ucl.ac.uk';                                                                                                                                                                                                     
    my $nnodes = '1';                                                                                                                                                                                                                     
    my $nprocs = '1'; # number of mpi processes                                                                                                                                                                                           
    my $cpuspertask = '1';                                                                                                                                                                                                                
    my $ntaskspernode = '1';                                                                                                                                                                                                              
                                                                                                                                                                                                                                          
    $extrarun = "";                                                                                                                                                                                                                       
    $datatransfer = "";                                                                                                                                                                                                                   
                                                                                                                                                                                                                                          
    $genericlaunchfile;                                                                                                                                                                                                                   
    $launchfile = "${dir}/launch_${jobname}_${dateidentifier}.sh";                                                                                                                                                                        
    $jobname .= "-${dateidentifier}";                                                                                                                                                                                                     
                                                                                                                                                                                                                                          
    open($in,'<',$genericlaunchfile) or die;                                                                                                                                                                                              
    open($out,'>',$launchfile) or die;                                                                                                                                                                                                    
                                                                                                                                                                                                                                          
    while(my $line = <$in>){                                                                                                                                                                                                              
                                                                                                                                                                                                                                          
        $line =~ s/JOBNAME/${jobname}/;                                                                                                                                                                                                   
        $line =~ s/DD/${dd}/;                                                                                                                                                                                                             
        $line =~ s/HH/${hh}/;                                                                                                                                                                                                             
        $line =~ s/MM/${mm}/;                                                                                                                                                                                                             
        $line =~ s/SS/${ss}/;                                                                                                                                                                                                             
        $line =~ s/EMAIL/${email}/;                                                                                                                                                                                                       
        $line =~ s/NODELIST/${nodename}/;                                                                                                                                                                                                 
        $line =~ s/NNODES/${nnodes}/;                                                                                                                                                                                                     
        $line =~ s/NTASKSPERNODE/${ntaskspernode}/;                                                                                                                                                                                       
        $line =~ s/CPUSPERTASK/${cpuspertask}/;                                                                                                                                                                                           
        $line =~ s/RUN/${runstring}/;                                                                                                                                                                                                     
        $line =~ s/EXTRA/${extrarun}/;                                                                                                                                                                                                    
        $line =~ s/DATATRANSFER/${datatransfer}/;                                                                                                                                                                                         
        print $out $line;                                                                                                                                                                                                                 
                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                     
    close($out);                                                                                                                                                                                                                          
    close($in);                                                                                                                                                                                                                           
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          
    if($run==1){                                                                                                                                                                                                                          
        $sbatchoutput = `sbatch $launchfile`;                                                                                                                                                                                             
        say $sbatchoutput;                                                                                                                                                                                                                
    }                                                                                                                                                                                                                                     
}        
