from datetime import date                                                                                                                                                                                                                 
from datetime import datetime                                                                                                                                                                                                             
import sys                                                                                                                                                                                                                                
import os                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                          
# mode                                                                                                                                                                                                                                    
run_mode = True                                                                                                                                                                                                                           
                                                                                                                                                                                                                                          
# user                                                                                                                                                                                                                                    
user = "ldavis"                                                                                                                                                                                                                           
                                                                                                                                                                                                                                          
# cdir                                                                                                                                                                                                                                    
cdir =f"/clusternfs/{user}/"                                                                                                                                                                                                              
                                                                                                                                                                                                                                          
# slurp in the slurm generic file                                                                                                                                                                                                         
generic_file = f"{cdir}launch_generic.sh"                                                                                                                                                                                                 
slurm_lines = []                                                                                                                                                                                                                          
with open(generic_file,'r') as gf:                                                                                                                                                                                                        
    slurm_lines = gf.readlines()                                                                                                                                                                                                          
                                                                                                                                                                                                                                          
##############################################################################################                                                                                                                                            
# Details of your program, in this case simple bash for loops                                                                                                                                                                             
dirr = f"/local/{user}/for_loop_test/"                                                                                                                                                                                                    
run_string = ""                                                                                                                                                                                                                           
run_string += f"mkdir -p {dirr}\n"                                                                                                                                                                                                        
Ns = range(0,12)                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          
for N in Ns:                                                                                                                                                                                                                              
    run_string += "for i in {"+f"1..{N}"+"}"+f"; do echo $i >> {dirr}{N}.txt; done &\n"                                                                                                                                                   
                                                                                                                                                                                                                                          
### put a small sleep just to check it is on the cluster okay                                                                                                                                                                             
run_string += "sleep 5m"                                                                                                                                                                                                                  
print(run_string)                                                                                                                                                                                                                         
##############################################################################################                                                                                                                                            
# now let's create a unique slurm script for our job, with a date and time stamped name for our records                                                                                                                                   
today = date.today()                                                                                                                                                                                                                      
now = datetime.now()                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          
now_string = now.strftime("%H_%M_%S")                                                                                                                                                                                                     
today_string = today.strftime("_%b_%d_%Y")                                                                                                                                                                                                
                                                                                                                                                                                                                                          
stamp = now_string + today_string                                                                                                                                                                                                         
print(stamp)                                                                                                                                                                                                                              
                                                                                                                                                                                                                                          
## variables for slurm                                                                                                                                                                                                                    
jname = "forlooptest"                                                                                                                                                                                                                     
dd = "00"                                                                                                                                                                                                                                 
hh = "00"                                                                                                                                                                                                                                 
mm = "30"                                                                                                                                                                                                                                 
ss = "00"                                                                                                                                                                                                                                 
ntasks = str(len(Ns))                                                                                                                                                                                                                     
cputask = "1"                                                                                                                                                                                                                             
modloads = ""                                                                                                                                                                                                                             
flags = ""                                                                                                                                                                                                                                
                                                                                                                                                                                                                                          
slurm_filename = f"{cdir}slurm_{stamp}.sh"                                                                                                                                                                                                
with open(slurm_filename,'w') as sf:                                                                                                                                                                                                      
    for line in slurm_lines:                                                                                                                                                                                                              
        line = line.replace("<NAME>",jname)                                                                                                                                                                                               
        line = line.replace("<DD>",dd)                                                                                                                                                                                                    
        line = line.replace("<HH>",hh)                                                                                                                                                                                                    
        line = line.replace("<MM>",mm)                                                                                                                                                                                                    
        line = line.replace("<SS>",ss)                                                                                                                                                                                                    
        line = line.replace("<NTASKS>",ntasks)                                                                                                                                                                                            
        line = line.replace("<CPUTASK>",cputask)                                                                                                                                                                                          
        line = line.replace("<MODULELOADS>",modloads)                                                                                                                                                                                     
                                                                                                                                                                                                                                          
        line = line.replace("<RUN>",run_string)                                                                                                                                                                                           
                                                                                                                                                                                                                                          
        sf.write(line)                                                                                                                                                                                                                    
                                                                                                                                                                                                                                          
# Run slurm if told to                                                                                                                                                                                                                    
if run_mode:                                                                                                                                                                                                                              
    os.system(f"sbatch {slurm_filename} {flags}")   
